spring:
  application:
    name: AdditionalProject

logging:
  level:
    root: info
    ru.get: debug
    org.springframework.web: info
    org.hibernate: error
  file:
    name: ./Logs/isBackend.log
  charset:
    console: UTF-8
    file: UTF-8